app/controllers/home_controller.py
from collections import defaultdict
from datetime import datetime

from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user

from app import mysql
from app.helpers import role_required

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return redirect(url_for('auth.login'))

import plotly.graph_objects as go

@main.route('/home', methods=['GET'])
@login_required
@role_required('manager')
def home():
    cursor = mysql.connection.cursor()

    # Lấy dữ liệu cho tháng này
    today = datetime.now().date()
    cursor.execute("""
            SELECT status, COUNT(*) AS count
            FROM attendance
            WHERE MONTH(check_in_time) = %s AND YEAR(check_in_time) = %s
            GROUP BY status
        """, (today.month, today.year))

    results = cursor.fetchall()
    cursor.close()

    # Khởi tạo số liệu thống kê cho tháng này
    status_counts = {'present': 0, 'late': 0, 'absent': 0}
    for row in results:
        status_counts[row[0]] = row[1]

    # Tạo biểu đồ tròn với Plotly
    fig_pie = go.Figure(data=[go.Pie(labels=['Đúng giờ', 'Trễ', 'Vắng'],
                                     values=[status_counts['present'], status_counts['late'], status_counts['absent']],
                                     textinfo='percent+label')])

    fig_pie.update_layout(title='Biểu đồ chấm công tháng này')

    # Lấy dữ liệu cho 12 tháng qua
    cursor = mysql.connection.cursor()
    cursor.execute("""
            SELECT MONTH(check_in_time) AS month, YEAR(check_in_time) AS year, status, COUNT(*) AS count
            FROM attendance
            WHERE YEAR(check_in_time) = %s
            GROUP BY YEAR(check_in_time), MONTH(check_in_time), status
            ORDER BY YEAR(check_in_time), MONTH(check_in_time)
        """, (today.year,))

    results = cursor.fetchall()
    cursor.close()

    # Khởi tạo số liệu thống kê cho 12 tháng qua
    stats_monthly = defaultdict(lambda: defaultdict(int))
    for row in results:
        month = f"{row[1]}-{row[0]}"  # Format: YYYY-MM
        status = row[2]
        count = row[3]
        stats_monthly[month][status] = count

    months = list(stats_monthly.keys())
    present_count = [stats_monthly[month].get('present', 0) for month in months]
    late_count = [stats_monthly[month].get('late', 0) for month in months]
    absent_count = [stats_monthly[month].get('absent', 0) for month in months]

    # Tạo biểu đồ cột với Plotly
    fig_bar = go.Figure(data=[
        go.Bar(name='Đúng giờ', x=months, y=present_count, marker_color='green'),
        go.Bar(name='Trễ', x=months, y=late_count, marker_color='orange'),
        go.Bar(name='Vắng', x=months, y=absent_count, marker_color='red')
    ])

    fig_bar.update_layout(
        barmode='stack',  # Để các cột chồng lên nhau
        title="Biểu đồ thống kê chấm công trong 12 tháng qua",
        xaxis_title="Tháng",
        yaxis_title="Số ca"
    )

    # Chuyển biểu đồ thành base64 để hiển thị trên website
    graph_pie = fig_pie.to_html(full_html=False)
    graph_bar = fig_bar.to_html(full_html=False)

    return render_template('home.html', graph_pie=graph_pie, graph_bar=graph_bar)




@main.route('/employee_dashboard')
@login_required
@role_required('employee')
def employee_dashboard():
    return render_template('employee_dashboard.html', full_name=current_user.full_name)

app/controllers/shift_controller.py
from collections import defaultdict
from datetime import timedelta, datetime

from flask import Blueprint, render_template, redirect, url_for, flash, request, jsonify
from flask_login import login_required
from app import mysql
from app.form.add_shift_form import ShiftForm
from app.helpers import role_required

shift = Blueprint('shift', __name__)

@shift.route('/shift/add', methods=['GET', 'POST'])
@login_required
@role_required('manager')
def add_shift():
    form = ShiftForm()

    if form.validate_on_submit():
        shift_name = form.shift_name.data
        start_time = form.start_time.data
        end_time = form.end_time.data

        cursor = mysql.connection.cursor()
        cursor.execute("""
            INSERT INTO shifts (shift_name, start_time, end_time)
            VALUES (%s, %s, %s)
        """, (shift_name, start_time, end_time))
        mysql.connection.commit()
        cursor.close()

        flash('Ca làm việc đã được thêm thành công!', 'success')
        return redirect(url_for('shift.shift_list'))

    return render_template('add_shift.html', form=form)


@shift.route('/shift/list', methods=['GET'])
@login_required
@role_required('manager')
def shift_list():
    cursor = mysql.connection.cursor()
    cursor.execute("SELECT id, shift_name, start_time, end_time FROM shifts")
    shifts = cursor.fetchall()
    cursor.close()

    return render_template('shift_list.html', shifts=shifts)


@shift.route('/shift/delete/<int:shift_id>', methods=['GET'])
@login_required
@role_required('manager')
def delete_shift(shift_id):
    # Tạo kết nối với cơ sở dữ liệu
    cursor = mysql.connection.cursor()

    # Xóa ca làm việc từ cơ sở dữ liệu
    cursor.execute("DELETE FROM shifts WHERE id = %s", (shift_id,))
    mysql.connection.commit()

    cursor.close()

    # Thông báo thành công và chuyển hướng về danh sách ca làm việc
    flash('Ca làm việc đã được xóa', 'success')
    return redirect(url_for('shift.shift_list'))


@shift.route('/shift/assign/<int:shift_id>', methods=['GET'])
@login_required
@role_required('manager')
def assign_employee_to_shift(shift_id):
    cursor = mysql.connection.cursor()

    # Lấy danh sách nhân viên chưa được gán vào ca làm việc này
    cursor.execute("""
        SELECT id, username, full_name FROM users
        WHERE id NOT IN (SELECT user_id FROM user_shift WHERE shift_id = %s)
        AND role != 'manager'
    """, (shift_id,))
    available_employees = cursor.fetchall()

    # Lấy danh sách nhân viên đã được gán vào ca làm việc này
    cursor.execute("""
        SELECT u.id, u.username, u.full_name FROM users u
        INNER JOIN user_shift us ON u.id = us.user_id
        WHERE us.shift_id = %s
    """, (shift_id,))
    assigned_employees = cursor.fetchall()

    cursor.close()

    return render_template('add_employee_to_shift.html', shift_id=shift_id,
                           employees=available_employees, assigned_employees=assigned_employees)


@shift.route('/shift/assign/<int:shift_id>', methods=['POST'])
@login_required
@role_required('manager')
def assign_employee_to_shift_post(shift_id):
    user_id = request.form['user_id']

    cursor = mysql.connection.cursor()

    # Kiểm tra nếu nhân viên đã được gán vào ca làm việc này
    cursor.execute("SELECT * FROM user_shift WHERE user_id = %s AND shift_id = %s", (user_id, shift_id))
    existing_assignment = cursor.fetchone()

    if existing_assignment:
        flash('Nhân viên này đã được gán vào ca làm việc này rồi', 'danger')
        return redirect(url_for('employee.assign_employee_to_shift', shift_id=shift_id))

    # Thêm nhân viên vào ca làm việc
    cursor.execute("""
        INSERT INTO user_shift (user_id, shift_id)
        VALUES (%s, %s)
    """, (user_id, shift_id))

    mysql.connection.commit()
    cursor.close()

    flash('Nhân viên đã được gán vào ca làm việc', 'success')
    return redirect(url_for('shift.assign_employee_to_shift', shift_id=shift_id))


@shift.route('/shift/remove_employee/<int:shift_id>/<int:user_id>', methods=['GET'])
@login_required
@role_required('manager')
def remove_employee_from_shift(shift_id, user_id):
    cursor = mysql.connection.cursor()

    # Xóa nhân viên khỏi ca làm việc trong bảng user_shift
    cursor.execute("""
        DELETE FROM user_shift
        WHERE shift_id = %s AND user_id = %s
    """, (shift_id, user_id))

    mysql.connection.commit()
    cursor.close()

    flash('Nhân viên đã được xóa khỏi ca làm việc', 'success')
    return redirect(url_for('shift.assign_employee_to_shift', shift_id=shift_id))


@shift.route('/api/shift/list', methods=['GET'])
def get_api_shift_list_by_user():
    # Lấy user_id từ tham số truy vấn
    user_id = request.args.get('user_id')

    if not user_id:
        return jsonify({"error": "User ID is required"}), 400

    try:
        # Mở một cursor mới cho kết nối MySQL
        cursor = mysql.connection.cursor()

        # Truy vấn để lấy thông tin ca làm việc từ bảng shifts, kết hợp với bảng user_shift
        query = """
            SELECT s.id, s.shift_name, s.start_time, s.end_time
            FROM shifts s
            JOIN user_shift us ON s.id = us.shift_id
            WHERE us.user_id = %s
            ORDER BY s.start_time ASC
        """
        cursor.execute(query, (user_id,))
        shifts = cursor.fetchall()

        cursor.close()

        # Nếu không có ca làm việc, trả về danh sách rỗng
        shift_list = []
        if shifts:
            # Chuyển đổi đối tượng datetime hoặc timedelta thành chuỗi để JSON có thể serializable
            for shift in shifts:
                start_time = shift[2]
                end_time = shift[3]

                # Kiểm tra nếu là timedelta và chuyển thành chuỗi
                if isinstance(start_time, timedelta):
                    # Nếu là timedelta, chuyển thành giờ và phút
                    start_time = str(start_time)
                elif isinstance(start_time, datetime):
                    # Nếu là datetime, định dạng theo HH:MM
                    start_time = start_time.strftime('%H:%M')

                if isinstance(end_time, timedelta):
                    # Nếu là timedelta, chuyển thành giờ và phút
                    end_time = str(end_time)
                elif isinstance(end_time, datetime):
                    # Nếu là datetime, định dạng theo HH:MM
                    end_time = end_time.strftime('%H:%M')

                shift_data = {
                    "id": shift[0],
                    "shift_name": shift[1],
                    "start_time": start_time,  # Chuyển đổi từ datetime hoặc timedelta
                    "end_time": end_time      # Chuyển đổi từ datetime hoặc timedelta
                }
                shift_list.append(shift_data)

        # Trả về danh sách ca làm việc dưới dạng JSON, có thể là danh sách rỗng
        return jsonify({"shifts": shift_list}), 200

    except Exception as e:
        return jsonify({"error": str(e)}), 500

@shift.route('/api/shift/history', methods=['GET'])
def get_attendance_history():
    user_id = request.args.get('user_id', type=int)

    if not user_id:
        return jsonify({"message": "User ID không hợp lệ"}), 400

    cursor = mysql.connection.cursor()
    cursor.execute("""
        SELECT attendance.id, shifts.shift_name, attendance.check_in_time, attendance.status
        FROM attendance
        JOIN shifts ON attendance.shift_id = shifts.id
        WHERE attendance.employee_id = %s
        ORDER BY attendance.check_in_time DESC
    """, (user_id,))

    attendance_records = cursor.fetchall()
    cursor.close()

    # If no attendance records, return an empty list
    if not attendance_records:
        return jsonify({"shifts": []})

    # Prepare the attendance records in a structured format
    shifts = [
        {
            "id": record[0],
            "shift_name": record[1],
            "check_in_time": record[2].strftime("%Y-%m-%d %H:%M:%S"),
            "status": record[3]
        }
        for record in attendance_records
    ]

    return jsonify({"shifts": shifts})

import requests
from decimal import Decimal
@shift.route('/employee/history/<int:user_id>', methods=['GET'])
def employee_history(user_id):
    # Kiểm tra tính hợp lệ của user_id
    if not user_id:
        return "User ID không hợp lệ", 400

    # Gọi API để lấy dữ liệu lịch sử chấm công
    response = requests.get(f'http://127.0.0.1:5000/api/shift/history?user_id={user_id}')

    if response.status_code != 200:
        return "Không thể lấy dữ liệu lịch sử chấm công", 500

    # Parse dữ liệu trả về từ API
    data = response.json()
    shifts = data.get('shifts', [])

    # Tính toán thống kê
    total_shifts = len(shifts)
    present_count = sum(1 for shift in shifts if shift['status'] == 'present')
    late_count = sum(1 for shift in shifts if shift['status'] == 'late')
    absent_count = sum(1 for shift in shifts if shift['status'] == 'absent')

    # Lấy mức lương cơ bản của nhân viên từ bảng users
    cursor = mysql.connection.cursor()
    cursor.execute("""
        SELECT salary FROM users WHERE id = %s
    """, (user_id,))
    salary = cursor.fetchone()[0]
    salary = Decimal(salary)

    # Tính tiền lương: salary * present_count + (salary * 10% của late_count)
    total_salary = salary * present_count + (salary * Decimal('0.10') * late_count)
    # Định dạng tiền tệ
    formatted_salary = "{:,.2f}".format(total_salary)
    # Trả về thống kê và tiền lương dưới dạng JSON
    stats = {
        "total_shifts": total_shifts,
        "present_count": present_count,
        "late_count": late_count,
        "absent_count": absent_count,
        "total_salary": formatted_salary  # Tiền lương tính toán được
    }

    # Render template và truyền dữ liệu cho template
    return render_template('employee_history.html', shifts=shifts, stats=stats)

app/templates/add_employee.html
{% extends 'layout.html' %}

{% block content %}
<div class="container-fluid p-2">
    <h2>{% if user %}Chỉnh sửa{% else %}Thêm{% endif %} Nhân Viên</h2>
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <div class="mb-3 position-relative">
            <label for="username" class="form-label">Tên Đăng Nhập</label>
            {{ form.username(class="form-control") }}
        </div>

        <div class="mb-3 position-relative">
            <label for="password" class="form-label">Mật Khẩu </label>
            {{ form.password(class="form-control") }}
        </div>

        <div class="mb-3 position-relative">
            <label for="full_name" class="form-label">Họ và Tên</label>
            {{ form.full_name(class="form-control") }}
        </div>

        <div class="mb-3 position-relative">
            <label for="dob" class="form-label">Ngày Sinh</label>
            {{ form.dob(class="form-control") }}
        </div>

        <div class="mb-3 position-relative">
            <label for="address" class="form-label">Địa Chỉ</label>
            {{ form.address(class="form-control") }}
        </div>

        <div class="mb-3 position-relative">
            <label for="phone" class="form-label">Số Điện Thoại</label>
            {{ form.phone(class="form-control") }}
        </div>

        <div class="mb-3 position-relative">
            <label for="email" class="form-label">Email</label>
            {{ form.email(class="form-control") }}
        </div>

        <div class="mb-3 position-relative">
            <label for="role" class="form-label">Vai Trò</label>
            {{ form.role(class="form-control") }}
        </div>

        <div class="mb-3 position-relative">
            <label for="salary" class="form-label">Lương</label>
            {{ form.salary(class="form-control") }}
        </div>
        <div class="mb-3 position-relative">
            <label for="face" class="form-label">Ảnh Khuôn Mặt</label>
            {{ form.face(class="form-control") }}
        </div>

        <div>
            <button type="submit" class="btn btn-primary">{% if user %}Lưu thay đổi{% else %}Thêm Nhân Viên{% endif %}</button>
        </div>
    </form>
</div>

{% endblock %}

app/templates/add_employee_to_shift.html
{% extends 'layout.html' %}

{% block title %}Thêm Nhân Viên Vào Ca Làm Việc{% endblock %}

{% block content %}
<div class="container-fluid p-2">
    <h2>Thêm Nhân Viên Cho Ca Làm Việc</h2>

    <form method="POST" action="{{ url_for('shift.assign_employee_to_shift', shift_id=shift_id) }}">
        <div class="mb-3">
            <label for="employee" class="form-label">Chọn Nhân Viên</label>
            <select class="form-select" name="user_id">
                {% for employee in employees %}
                    <option value="{{ employee[0] }}">{{ employee[2] }} ({{ employee[1] }})</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Thêm Nhân Viên Vào</button>
    </form>

    <h2 class="mt-4">Danh Sách Nhân Viên Trong Ca Làm Việc</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>STT</th>
                <th>Tên Đăng Nhập</th>
                <th>Họ và Tên</th>
                <th>Chức Vụ</th>
                <th>Hành động</th>
            </tr>
        </thead>
        <tbody>
            {% for assigned_employee in assigned_employees %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ assigned_employee[1] }}</td>
                    <td>{{ assigned_employee[2] }}</td>
                    <td>
                        {% if assigned_employee[3] == 'manager' %}
                            Quản Lý
                        {% else %}
                            Nhân Viên
                        {% endif %}
                    </td>
                    <td class="table-action">
                        <a href="{{ url_for('shift.remove_employee_from_shift', shift_id=shift_id, user_id=assigned_employee[0]) }}" class="action-icon">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                    </td>
                </tr>

            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/add_shift.html
{% extends 'layout.html' %}

{% block title %}Thêm Ca Làm Việc{% endblock %}

{% block content %}
<div class="container-fluid p-2">
    <h2>Thêm Ca Làm Việc</h2>
    <form method="POST">
        {{ form.hidden_tag() }}

        <div class="mb-3 position-relative">
            <label for="shift_name" class="form-label">Tên Ca Làm Việc</label>
            {{ form.shift_name(class="form-control") }}
        </div>

        <div class="mb-3 position-relative">
            <label for="start_time" class="form-label">Thời gian bắt đầu</label>
            {{ form.start_time(class="form-control") }}
        </div>

        <div class="mb-3 position-relative">
            <label for="end_time" class="form-label">Thời gian kết thúc</label>
            {{ form.end_time(class="form-control") }}
        </div>

        <div>
            <button type="submit" class="btn btn-primary">Thêm Ca Làm Việc</button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/attendance_statistics.html
{% extends 'layout.html' %}

{% block title %}Danh Sách Ca Làm Việc{% endblock %}

{% block content %}
<div class="container">
        <h1>Thống kê Chấm Công</h1>

        <!-- Biểu đồ tròn cho tháng này -->
        <div>
            <h3>Biểu đồ chấm công tháng này</h3>
            {{ graph_pie|safe }}
        </div>

        <!-- Biểu đồ cột cho 12 tháng qua -->
        <div>
            <h3>Biểu đồ thống kê chấm công 12 tháng qua</h3>
            {{ graph_bar|safe }}
        </div>
    </div>

{% endblock %}

app/templates/employee_history.html
{% extends 'layout.html' %}

{% block title %}Lịch Sử Chấm Công{% endblock %}

{% block content %}
<div class="container-fluid p-2">


    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">Thống Kê Chấm Công của Nhân Viên</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <!-- Thống kê tổng quan -->
    <div class="row">
        <!-- Tổng số ca -->
        <div class="col-lg-6 col-xl-3">
            <div class="card">
                <div class="card-body text-center">
                    <h5 class="card-title">Tổng số ca</h5>
                    <p class="card-text"><b>{{ stats.total_shifts }}</b></p>
                </div>
            </div>
        </div>

        <!-- Đúng giờ -->
        <div class="col-lg-6 col-xl-3">
            <div class="card">
                <div class="card-body text-center">
                    <h5 class="card-title">Đúng giờ</h5>
                    <p class="card-text" style="color: green;"><b>{{ stats.present_count }}</b></p>
                </div>
            </div>
        </div>

        <!-- Trễ -->
        <div class="col-lg-6 col-xl-3">
            <div class="card">
                <div class="card-body text-center">
                    <h5 class="card-title">Đi trễ</h5>
                    <p class="card-text" style="color: orange;"><b>{{ stats.late_count }}</b></p>
                </div>
            </div>
        </div>
        <!-- Tiền lương -->
        <div class="col-lg-6 col-xl-3">
            <div class="card">
                <div class="card-body text-center">
                    <h5 class="card-title">Tiền lương hiện tại</h5>
                    <p class="card-text" style="color: orange;"><b>{{ stats.total_salary }} đ</b></p>
                </div>
            </div>
        </div>
    </div>

    <!-- end row-->

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">Lịch sử chấm công của nhân viên</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-centered display table-list" style="width: 100%">
                            <thead class="table-light">
                                <tr>
                                    <th class="d-none d-xl-table-cell">STT</th>
                                    <th class="d-none d-xl-table-cell">Tên Ca Làm Việc</th>
                                    <th class="d-none d-md-table-cell">Thời gian Check-In</th>
                                    <th class="d-none d-md-table-cell">Trạng thái</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for shift in shifts %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td>{{ shift.shift_name }}</td>
                                    <td>{{ shift.check_in_time }}</td>
                                    <td>
                                        {% if shift.status == 'present' %}
                                        <div class="text-success">Đã điểm danh</div>
                                        {% elif shift.status == 'late' %}
                                        <div class="text-warning">Trễ làm</div>
                                        {% else %}
                                        <div class="text-danger">Không chấm công</div>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- end card-body-->
            </div>
            <!-- end card-->
        </div>
        <!-- end col -->
    </div>
    <!-- end row -->
</div>
{% endblock %}

app/templates/employee_list.html
{% extends 'layout.html' %}

{% block title %}Danh Sách Nhân Viên{% endblock %}

{% block content %}
<div class="container-fluid p-2">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">Danh sách nhân sự</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col-sm-4">
                            <a href="{{ url_for('employee.add_or_edit_employee') }}" class="btn btn-primary mb-2"><i class="mdi mdi-plus-circle me-2"></i> Thêm nhân viên mới</a>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-centered display table-list" style="width: 100%">
                            <thead class="table-light">
                                <tr>
                                    <th class="d-none d-xl-table-cell">STT</th>
                                    <th class="d-none d-xl-table-cell">Tên Đăng nhập</th>
                                    <th class="d-none d-md-table-cell">Họ và tên</th>
                                    <th class="d-none d-md-table-cell">Email</th>
                                    <th class="d-none d-md-table-cell">Số điện thoại</th>
                                    <th class="d-none d-md-table-cell">Lương</th>
                                    <th class="d-none d-md-table-cell">Trạng thái</th>
                                    <th style="width: 85px;">Hành động</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in users %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td>
                                        <p class="m-0 d-inline-block align-middle font-16">
                                            <a href="{{ url_for('shift.employee_history', user_id=user[0]) }}" class="text-body">{{ user[1] }}</a>
                                        </p>
                                    </td>
                                    <td>{{ user[2] }}</td>
                                    <td>{{ user[3] }}</td>
                                    <td>{{ user[4] }}</td>
                                    <td>
                                        {{user[5]}}
                                    </td>
                                    <td>
                                        {% if user[6] == 1 %}
                                        <div class="text-success">Đang sử dụng</div>
                                        {% else %}
                                        <div class="text-danger">Đang khóa</div>
                                        {% endif %}
                                    </td>

                                    <td class="table-action">
                                        <a href="{{ url_for('employee.add_or_edit_employee', user_id=user[0]) }}" class="action-icon">
                                            <i class="fa-solid fa-pen"></i>
                                        </a>
                                        <a href="{{ url_for('employee.lock_employee', user_id=user[0]) }}" class="action-icon">
                                            <i class="fa-solid fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- end card-body-->
            </div>
            <!-- end card-->
        </div>
        <!-- end col -->
    </div>
    <!-- end row -->
</div>
{% endblock %}

app/templates/employee_salary_detail.html
{% extends 'layout.html' %}

{% block title %}Chi Tiết Nhân Viên{% endblock %}

{% block content %}
<div class="container">
    <h1>Thông Tin Nhân Viên</h1>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Tên Nhân Viên: {{ employee.full_name }}</h5>
            <p><strong>Lương Cơ Bản:</strong> {{ employee.salary }} VND / Ca</p>
        </div>
    </div>

    <h2>Ca Chấm Công Chưa Thanh Toán</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tên Ca</th>
                <th>Giờ Vào</th>
                <th>Trạng thái</th>
            </tr>
        </thead>
        <tbody>
            {% for attendance in employee.attendance_details %}
                <tr>
                    <td>{{ attendance.attendance_id }}</td>
                    <td>{{ attendance.shift_name }}</td>
                    <td>{{ attendance.check_in_time }}</td>
                    <td>{{ attendance.status}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Tổng Tiền Thanh Toán: {{ employee.total_payment }} VND</h3>

    <form method="POST" action="{{ url_for('employee.pay_salary', employee_id=employee.employee_id) }}">
        <button type="submit" class="btn btn-success">Thanh Toán</button>
    </form>
</div>
{% endblock %}

app/templates/shift_list.html
{% extends 'layout.html' %}

{% block title %}Danh Sách Ca Làm Việc{% endblock %}

{% block content %}
<div class="container-fluid p-2">
    <h2>Danh Sách Ca Làm Việc</h2>
    
    <div class="row mb-2">
        <div class="col-sm-4">
            <a href="{{ url_for('shift.add_shift') }}" class="btn btn-primary mb-2">
                <i class="mdi mdi-plus-circle me-2"></i> Thêm Ca Làm Việc
            </a>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-centered display table-list" style="width: 100%">
            <thead class="table-light">
                <tr>
                    <th class="d-none d-xl-table-cell">STT</th>
                    <th class="d-none d-md-table-cell">Tên Ca Làm Việc</th>
                    <th class="d-none d-md-table-cell">Thời Gian Bắt Đầu</th>
                    <th class="d-none d-md-table-cell">Thời Gian Kết Thúc</th>
                    <th style="width: 85px;">Hành Động</th>
                </tr>
            </thead>
            <tbody>
                {% for shift in shifts %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ shift[1] }}</td>
                    <td>{{ shift[2] }}</td>
                    <td>{{ shift[3] }}</td>
                    <td class="table-action">

                        <a href="{{ url_for('shift.assign_employee_to_shift', shift_id=shift[0]) }}" class="action-icon" >
                            <i class="fa-solid fa-users"></i>
                        </a>
                        <a href="{{ url_for('shift.delete_shift', shift_id=shift[0]) }}" class="action-icon">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}